config/routes.rb
Rails.application.routes.draw do
  resources :listings
  root 'listings#index'
  #get 'listings/index'

  #get 'listings/new'


end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates_presence_of :house_type
	validates_presence_of :location
  	validates :contact_infor, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
  	@listings = Listing.all
  end

  def new
  	@listing = Listing.new
  end
  def create 
  	@listing = Listing.new(listing_params)
  	if @listing.save
  		redirect_to root_path
  	else
  		render new
  	end
  end

  private 
  def listing_params
      params.require(:listing).permit(:house_type, :location, :contact_infor)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unlimihouse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/listings/index.html.erb
<h1>Property Listings</h1>
<% @listings.each do |listing| %>
  <div class="listing">
    <h2><%= link_to listing.house_type, listing.contact_infor %></h2>
    <p><%= listing.location %>
  </div>
<% end %>
<p><%= link_to "Add Property Listing", new_listing_path %></p>

app/views/listings/new.html.erb
<%= simple_form_for @listing do |form| %>
  <%= form.input :house_type, label: "House type" %>
  <%= form.input :location, label: "Location" %>
  <%= form.input :contact_infor, label: "Management contact" %>
  <%= form.button :submit %>
<% end %>